// FILE PATH: src/lib/openapi-builder.ts
/**
 * Assembles the final OpenAPI 3.1 document from adapter output.
 *
 * Ensures deterministic output: paths sorted alphabetically, methods sorted
 * in a canonical order. Same input → same output byte-for-byte.
 */

import type {
  HttpMethod,
  OpenAPIDocument,
  OpenAPIPathItem,
} from "../types.js";

const EXTRACTOR_VERSION = "0.1.0";

const METHOD_ORDER: HttpMethod[] = [
  "get", "post", "put", "patch", "delete", "options", "head",
];

export type BuildOptions = {
  title?: string;
  framework: string;
  generatedAt?: Date;
};

export function buildOpenAPIDocument(
  paths: Record<string, OpenAPIPathItem>,
  options: BuildOptions,
): OpenAPIDocument {
  const generatedAt = options.generatedAt ?? new Date();

  const sortedPaths: Record<string, OpenAPIPathItem> = {};
  for (const key of Object.keys(paths).sort()) {
    sortedPaths[key] = sortMethods(paths[key]!);
  }

  return {
    openapi: "3.1.0",
    info: {
      title: options.title ?? "API",
      version: "1.0.0",
      description:
        `Generated by @stoney-dev/extractor from static analysis of ` +
        `${options.framework} source code.`,
      "x-generated-by": "@stoney-dev/extractor",
      "x-generated-at": generatedAt.toISOString(),
      "x-extractor-version": EXTRACTOR_VERSION,
    },
    paths: sortedPaths,
  };
}

function sortMethods(pathItem: OpenAPIPathItem): OpenAPIPathItem {
  const sorted: OpenAPIPathItem = {};
  for (const method of METHOD_ORDER) {
    if (pathItem[method]) sorted[method] = pathItem[method];
  }
  return sorted;
}
